// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SM.Medication.Infrastructure.Persistence;

#nullable disable

namespace SM.Medication.Infrastructure.Migrations
{
    [DbContext(typeof(SmartMedMedicationDbContext))]
    [Migration("20240726082831_InitialDataBase")]
    partial class InitialDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SM.Medication.Domain.Entities.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.HasKey("Id");

                    b.ToTable("Medication", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 7, 26, 8, 28, 30, 203, DateTimeKind.Utc).AddTicks(2807),
                            CreatedBy = "DbContext",
                            ModifiedAt = new DateTime(2024, 7, 26, 8, 28, 30, 203, DateTimeKind.Utc).AddTicks(2809),
                            ModifiedBy = "DbContex",
                            Name = "Paracetamol",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 7, 26, 8, 28, 30, 203, DateTimeKind.Utc).AddTicks(2811),
                            CreatedBy = "DbContext",
                            ModifiedAt = new DateTime(2024, 7, 26, 8, 28, 30, 203, DateTimeKind.Utc).AddTicks(2811),
                            ModifiedBy = "DbContex",
                            Name = "Ibuprofen",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 7, 26, 8, 28, 30, 203, DateTimeKind.Utc).AddTicks(2813),
                            CreatedBy = "DbContext",
                            ModifiedAt = new DateTime(2024, 7, 26, 8, 28, 30, 203, DateTimeKind.Utc).AddTicks(2813),
                            ModifiedBy = "DbContex",
                            Name = "Aspirin",
                            Quantity = 75
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
